
export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';

export const ADD_FAVORITES = 'ADD_FAVORITES';
export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';
export const REMOVE_ALL_FAVORITES = 'REMOVE_ALL_FAVORITES';
export const GET_LOCALSTORAGE_FAVS = 'GET_LOCALSTORAGE_FAVS';

export const ERROR_CONFIRMED = 'ERROR_CONFIRMED';

export const MODE_SELECTOR = 'MODE_SELECTOR';
